### ISSUE TITLE
Update QSDsan capacity pages

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#106]
Open an issue here so I don't forget! Refer to the internal email for details, but the idea is to have a page that shows what is currently in QSDsan. In the past we have a page for the developed [processes](https://qsdsan.readthedocs.io/en/latest/api/processes/_index.html), [unit operations](https://qsdsan.readthedocs.io/en/latest/api/sanunits/_index.html), and [systems](https://qsdsan.readthedocs.io/en/latest/Developed_Systems.html), but I haven't updated it for quite some time.

Additionally, since we are developing the benchmarking configurations, it'll be great if we can have one page dedicated to it (or add to existing pages).

**Comment by joyxyz1994** [comment]
I'm leaning toward adding the benchmark configurations into the "systems" page. Many of the unit operations and process models are already included in the developed "processes" and "unit operations".

**Comment by yalinli2** [comment]
sounds good, could have one section that list the 25 configurations (and I gonna steal the nice figure you made) 😉 

I'll make this my homework before next week's coordination call

**Comment by yalinli2** [comment]
note that I also want to add the link to the tutorial slides @GaYeongKim is developing and update the developer page to acknowledge the new contributors

**Comment by joyxyz1994** [comment]
No problem. Let me send you the original file of that figure.

**Comment by yalinli2** [comment]
hmmmmm I updated the pages but somehow one test failed:
https://github.com/QSD-Group/QSDsan/actions/runs/6375099195

It's not related to what I changed, and my local tests (even after I updated my local `matplotlib`) all pass, no clue why this is happening, @joyxyz1994 can you pull `beta` and see if tests pass on your end? Thanks!

**Comment by yalinli2** [comment]
Done in #107!
