### ISSUE TITLE
TypeError in create_MODEL_cmps: CompiledChemicals._compile() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by pengxiao01** [QSD-Group/QSDsan#123]
**Describe the problem**
While trying to create state variables for MODEL (e.g., ADM1/ASM2D) using create_madm1_cmps(), I encountered a TypeError. It seems that CompiledChemicals._compile() is being called with 3 positional arguments, but the method only accepts 2. Below is the relevant code and error traceback:

**To Reproduce**
1. Import processes from qsdsan:
from qsdsan import processes as pc
cmps = pc.create_madm1_cmps()  # create state variables for ADM1
cmps.show()
2. Run the script.

**Screenshots**
![Screenshot 2024-09-30 at 11 08 08](https://github.com/user-attachments/assets/2c7db583-c697-49c9-9799-3290030a637b)

**Environment (please complete the following information):**
1. Versions of the following packages:
     - QSDsan 1.3.1
     - EXPOsan (if applicable)
     - BioSTEAM 2.46.1

    If you are using pip-installed ones, you can get the info by `pip show <PACKAGE_NAME>` (e.g., `pip show qsdsan`).

    If you have cloned any of the following packages, please make sure your local and remote are in sync (either pull remote changes to local or push local changes to remote), then include links or point to the branches/forks you are using.

3. Operating systems and version [e.g. macOS 12.1, Windows 11]
Linux (Google Colab)

**Additional context**

**Comment by joyxyz1994** [comment]
Hi @pengxiao01, thanks for notifying us the issue. 

The modified ADM1 related features aren't available in the pip-installed version of QSDsan yet. We're working on a new release. In the meantime, please use the [`dev` branch](https://github.com/QSD-Group/QSDsan/tree/dev/qsdsan) of the Github version of QSDsan to access those feature. If you're also using EXPOsan, the [`bsm2` branch ](https://github.com/QSD-Group/EXPOsan/tree/bsm2) is the compatible version.

**Comment by yalinli2** [comment]
This is actually due to a recent update in BioSTEAM, @pengxiao01 you probably installed the pip version of BioSTEAM (or pulled the `master` branch instead of the `qsdsan` branch). It should be fixed now if you update your env.
