### ISSUE TITLE
Review changes in WasteStream and Components

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#39]
Hi @joyxyz1994 , I was pulling your changes on processes and found some minor issues, can you review the following and see if they look good to you? If it's good then I'll push to the main branch.
- In 5350eb0bf204316f8a64108a2280b70ec59a7b0f, `set_flow_by_concentration` in _waste_stream.py, lines 855 and 865
- In 9905fcfe9fd73118aac4358374b067ac377a27d7, in _components.py, I'm using `ID` instead of `CAS` now, because there might be cases where people want to have two components fixed at different phases of the same chemical (just had a call with Shion and she wanted to have a gas phase CH4 and soluble CH4. If using CAS then the soluble CH4 won't be added in the `Components`.

Thanks!

**Comment by joyxyz1994** [comment]
Hi @yalinli2, thanks for fixing the codes! I think it's actually better to use `ID` than `CAS` for `Components`. Original `CAS` was used simply to be consistent with `Chemicals`. You can go ahead and push the changes to the main branch. Thanks!

**Comment by yalinli2** [comment]
Cool! Pushed to the main branch 83f221e9ed6e737307c36bdb641c1fb6eaecdf8a, thanks Joy!
