### ISSUE TITLE
`WasteStream` models need updating

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#40]
Hey @joyxyz1994, I got some errors while making the tutorial, I think IDs of some of the `Component` have been updated, but not yet reflected in the models (e.g., `SU_Inf` below should probably be `S_U_Inf`).

https://github.com/QSD-Group/QSDsan/blob/dc5b7b7202bb514afa13815ed01a056873436450/qsdsan/_waste_stream.py#L1253

Can you take a look and update as needed? Thanks!

**Comment by joyxyz1994** [comment]
Hi @yalinli2, it should be fixed now. Let me know if you run into any other problem! Thanks!

**Comment by yalinli2** [comment]
Yep I think it's fixed, thanks Joy!
