### ISSUE TITLE
Clean up legacy comments

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#57]
Need to to addressed or removed if it's outdated, listed by units in following posts

General ones:
- breakpoints if you've done debugging, they shouldn't be there

**Comment by yalinli2** [comment]
`ScrewPress`:
- https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_screw_press.py#L87
- https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_screw_press.py#L102
- https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_screw_press.py#L113

**Comment by yalinli2** [comment]
`CabonizerBase`:
- These emissions aren't there: https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_carbonizer_base.py#L64 
- Adding cost this would prevent the price of stainless steel, etc. from being updated to the same price across system (should've set the price of the corresponding impact items) https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_carbonizer_base.py#L209

**Comment by yalinli2** [comment]
`PollutionControlDevice` (in addition to above):
- It should be in kg/hr, not g/hr https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_pollution_control_device.py#L106

**Comment by yalinli2** [comment]
`DryerFromHHX`
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_dryer_from_hhx.py#L49

**Comment by yalinli2** [comment]
`IonExchangeNH3`
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_ion_exchange_NH3.py#L173

**Comment by haclohman** [comment]
Finished for SCG Aquonic.

**Comment by yalinli2** [comment]
Cool, thanks @haclohman , can you pull changes from main so that your branch isn't behind? I'll try to take a look this week, thanks!

**Comment by haclohman** [comment]
> 

Done!

**Comment by yalinli2** [comment]
After @lsrowles posted the differences between his local codes and the GitHub version, I'll do a sweep for BR's units and remove the legacy comments (I've done this for the `biogenic_module` in EXPOsan )

**Comment by yalinli2** [comment]
I think this is largely done, I'll give the codes another look when merging them into the `main` branch
