### ISSUE TITLE
References in units/data sheets

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#58]
Many of the new units does not have documentation/references, some that stands out:
- In the [data sheet](https://github.com/QSD-Group/QSDsan/blob/BR_OmniProcessor/qsdsan/data/sanunit_data/_screw_press.tsv) of `ScrewPress`, not sure what the "Additional Questions" is, and what that "dewatering_energy_demand_old" is doing

**Comment by haclohman** [comment]
Finished for SCG Aquonic.

**Comment by lsrowles** [comment]
dewatering_energy_demand_old can be removed from the ScrewPress. I am updating all the datasheets to only include required parameters and add references where missing.

**Comment by yalinli2** [comment]
Awesome!!!

**Comment by yalinli2** [comment]
Stetson has cleaned up the data sheets for BR units

**Comment by shionwatabe** [comment]
Finished for NEWgenerator :)

**Comment by haclohman** [comment]
Updated references for Reclaimer on the public repo.

**Comment by yalinli2** [comment]
Great! I'll take a final look on the docs of all the systems and close this

**Comment by yalinli2** [comment]
OK all look good now and docs are updated!
