### ISSUE TITLE
`SanUnit.__init__`

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#59]
Many of the the `__init__` methods are error-prone, e.g.,

```python
    def __init__(self, ID='', ins=None, outs=(), **kwargs):
        SanUnit.__init__(self, ID, ins, outs, F_BM_default=1)
```

This won't allow the unit to init with the correct `thermo` object and stream types, please update those to be

```python
    def __init__(self, ID='', ins=None, outs=(), thermo=None, init_with='WasteStream',
                 **kwargs):
        SanUnit.__init__(self, ID, ins, outs, thermo=thermo, init_with=init_with,
                         F_BM_default=1)
```

Please DO modify this based on your units - e.g., some units' might other other attributes (e.g., `lifetime`, `CAPEX_over_OPEX` that need to be included)

**Comment by haclohman** [comment]
Finished for SCG Aquonic.

**Comment by yalinli2** [comment]
Forgot to note that this is done for BR as well, on the `gates` branch

**Comment by shionwatabe** [comment]
Finished for NEWgenerator :)

**Comment by yalinli2** [comment]
I think this is largely done, any remaining ones will be updated when I merge `gates` into `main`
