### ISSUE TITLE
Workflow to merge branches into `gates`

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#61]
We need to standardize the codes before I'm comfortable with including them into the main branch and on PyPI, I'm doing this myself for the `BR_OmniProcessor` because it is the [closest](https://github.com/QSD-Group/QSDsan/branches) (i.e., least behind) among all, but I'd really appreciate help, specifically
- Make sure no error and no warning (i.e., related to `F_BM`) when running the system
    - Also no warnings/errors from the editor (e.g., no yellow triangles from Spyder) 
![Screen Shot 2022-02-25 at 1 25 17 PM](https://user-images.githubusercontent.com/49011373/155775749-1af0a470-145e-481e-af7b-ba29c2a7c123.png)

- Clean up legacy comments, breakpoints, "#!!!", "TODO", etc.
- If you copy something from another module, make sure you update the variable names, comments, etc. to the existing module
- If there are codes that you don't understand, try to find who wrote that, if you can't figure it out, open an issue here on GitHub
- Check the data sheet and make sure they look good, remove legacy data like "XXX_old", see #58 
- Add documentation, at the minimum you should provide description of the unit (including what components and impact items are needed for the unit, see #51) as well as the reference.
- Rerun the corresponding systems and make sure the results match

**Comment by yalinli2** [comment]
We'll also want to discuss the priorities of merging, my current plan is
- Paper-related systems first
- Public > private
- Least outdated first

**Comment by haclohman** [comment]
Finished for SCG Aquonic.

**Comment by yalinli2** [comment]
And `scg_aquonic` is merged into `gates` 😊

**Comment by yalinli2** [comment]
Realized that I forgot to explain what is `gates`, so instead of merging into `main`, I made a new branch of `gates` and we will use it as a working branch until it has a good structure, all new units have detailed documentation and test modules, etc.

This process may take quite some time, so having a temporary branch is probably the best way to handle it
> And `scg_aquonic` is merged into `gates` 😊

**Comment by shionwatabe** [comment]
Finished for NEWgenerator, but still need to run to make sure it works (might need to update biosteam?)

**Comment by yalinli2** [comment]
> Finished for NEWgenerator, but still need to run to make sure it works (might need to update biosteam?)

Yes you'll definitely want to update biosteam/thermosteam

**Comment by yalinli2** [comment]
I believe all systems have been merged into the `gates` branch, there are still the legacy `BR_OmniProcessor` branch and the `newgen` branch leaving out as they are used in the analyses for manuscript (the newer versions are in the gates branch now), but they will be archived once the manuscripts are published
