### ISSUE TITLE
Question on IonExchangeNH3

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#65]
- What if the number of column is not divisible by 3 (e.g., how many tanks do we need for 10 columns)?
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_ion_exchange_NH3.py#L142
- Is these cost used anywhere? They should be included as an operating cost
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_ion_exchange_NH3.py#L115
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_ion_exchange_NH3.py#L121

**Comment by yalinli2** [comment]
NEWgen & Reclaimer use zeolite (adsorbent, resin, a general term), have diff weights & regeneration freq., 

NEWgen & Reclaimer also have GAC, process is the same, just cost/materials

See if it's better for 1 unit or different ones

**Comment by yalinli2** [comment]
acid_cost_day, resin_cost_day not needed, tank quantity to be discussed

**Comment by lsrowles** [comment]
The assumption here is that one 300 L tank has an average of three columns. Tank quantity were added here to calculate the amount of polyethylene as well as the tank cost.

**Comment by yalinli2** [comment]
Calculation of `acid_cost_day` and `resin_cost_day` have been removed, allowing `Tank_quant` to be floats (instead of using `ceil`
