### ISSUE TITLE
Question on Grinder

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#66]
- Can grinder remove moisture? If so, should include in the description of the class, right now it only says it breaks up the solids
    - Then where does the water go? There's only one influent and one effluent
    - The calculation here is assuming a moisture content of 65%, not 35%
https://github.com/QSD-Group/QSDsan/blob/e9fdbf1e6ed25685ce31093f5a58eced6c5eabc7/qsdsan/sanunits/_grinder.py#L94
- Is `price_ratio` needed here?

**Comment by yalinli2** [comment]
Grinder cannot remove moisture, but have to make the assumption here for the system to run properly, the moisture content should be 65%

**Comment by yalinli2** [comment]
`price_ratio` was not added because this system is highly specialized, so the price shouldn't be adjusted based on the where the system is implemented.

**Comment by yalinli2** [comment]
Parts that might be built with the deployment country: grinder, screw press (i.e., pretreatment/side treatment units), but not the biogenic refinery system

**Comment by lsrowles** [comment]
The grinder is only used to break up the solids from UDDT into smaller pieces. The assumption for moisture content is only so the system can run properly. These assumptions seem to be reasonable based on the pilot studies (other inputs with higher moisture content may require additional water removal).

**Comment by yalinli2** [comment]
Default moisture content has been updated to 65% in the `gates` branch, a note was added in the documentation of this unit about this assumption.

Refer to #54 for the discussion on the `price_level_ratio`
