### ISSUE TITLE
BioSTEAM's QDSsan test not running.

### ISSUE THREAD

**Issue by yoelcortes** [QSD-Group/QSDsan#72]
Hi! 

Just a heads up, I think the latest qsdsan merge had some name changes that stop BioSTEAM's QDSsan test from running.

**To Reproduce**
Input:
```python
def test_dyn_sys():
    from qsdsan import processes as pc, sanunits as su, set_thermo, System
    import numpy as np
    from numpy.testing import assert_allclose
    cmps = pc.load_asm1_cmps()
test_dyn_sys()
```
Output:
```python
AttributeError: module 'qsdsan.processes' has no attribute 'load_asm1_cmps'
```

**Environment**
Windows 11, latest github versions of all the following:
     - QSDsan
     - EXPOsan 
     - BioSTEAM
     - Thermosteam

**Comment by yalinli2** [comment]
Ahhh I forgot to fix biosteam's tests, it's fixed now and thanks @yoelcortes for posting the issue!

PS, sleek new doc page for biosteam/thermosteam!
