### ISSUE TITLE
Question related to PitLatrine emptying ratio

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#99]
Open this issue to remind myself about a question from this week's office hour (3/6/23). The question is about why the truck trip increases when increasing `PitLatrine.emptying_ratio`

**Comment by BackFett** [comment]
Hi! This comment was related to PitLatrine.emptying_period. It was because I used "truck.interval = A2.emptying_period*365*24". After setting the Trucking.interval to a standard time (12hr) the emptying_period doesn´t affect the number of parallel trucks any more.

**Comment by yalinli2** [comment]
ah I see, thanks @BackFett for letting me know!
